name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Install Homepage dependencies
        run: |
          cd Homepage/HomepageCode
          npm ci

      - name: Build Homepage app
        run: |
          cd Homepage/HomepageCode
          npm run build -- --configuration production
      
      - name: Install netlify-cli
        run: |
          npm install -g netlify-cli

      - name: Create _redirects for Netlify
        run: |
          echo '/*    /index.html   200' > Homepage/HomepageCode/dist/Homepage/browser/

      - name: Prepare deployment folder
        run: |
          mkdir pages
          find . -mindepth 1 -maxdepth 1 ! -name 'pages' ! -name '.github' -exec cp -r {} pages/ \;
          mv Homepage/HomepageCode/dist/Homepage/browser/* pages
          rm -rf pages/Homepage

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: Homepage/HomepageCode/dist/Homepage/browser/
          production-branch: main
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          site-id: ${{ secrets.NETLIFY_SITE_ID }}
